# Generated by Django 5.1.2 on 2026-01-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('USA', 'USA'), ('Brazil', 'Brazil'), ('Morocco', 'Morocco'), ('India', 'India')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artworks/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='artworks/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
