# Generated by Django 5.1.2 on 2026-02-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artist_delete_artistprofile_artwork_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='country',
        ),
    ]
