# Generated by Django 5.1.2 on 2026-02-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_artist_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='role',
            field=models.CharField(choices=[('Team Leader', 'Team Leader'), ('Artist', 'Artist'), ('Other', 'Other')], default='Artist', max_length=50),
        ),
    ]
