# Generated by Django 5.1.2 on 2026-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_artist_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('USA', 'USA'), ('Brazil', 'Brazil'), ('Morocco', 'Morocco'), ('India', 'India'), ('UAE', 'UAE')], max_length=50),
        ),
    ]
