# Generated by Django 5.1.2 on 2026-02-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_artwork_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
