# Generated by Django 5.1.2 on 2026-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_artist_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='activities/videos/')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date'],
            },
        ),
    ]
