# Generated by Django 5.1.2 on 2026-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
