# Generated by Django 5.1.2 on 2026-02-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_artwork_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Must match the category name in Artwork (e.g., 'Morocco', 'Brazil')", max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AlterField(
            model_name='artist',
            name='role',
            field=models.CharField(choices=[('Team Leader', 'Project Leader'), ('Artist', 'Artist'), ('Other', 'Other')], default='Artist', max_length=50),
        ),
    ]
