# Generated by Django 5.1.2 on 2026-02-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_country_alter_artist_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='core.country'),
        ),
    ]
