# Generated by Django 5.1.2 on 2026-02-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_artwork_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
    ]
